const { colors } = require('tailwindcss/defaultTheme')

module.exports = {
  theme: {
    screens: {
      sm: '640px',
      lg: '1024px',
    },
    colors: {
      black: colors.black,
      white: colors.white,
      gray: colors.gray,
      red: colors.red,
    },
    spacing: {
      '0': '0',
      '1': '0.25rem',
      '2': '0.5rem',
      '3': '0.75rem',
      '4': '1rem',
      '6': '1.5rem',
      '8': '2rem',
    },
    fontFamily: {
      sans: [
        '-apple-system',
        'BlinkMacSystemFont',
        '"Segoe UI"',
        'Roboto',
        '"Helvetica Neue"',
        'Arial',
        '"Noto Sans"',
        'sans-serif',
        '"Apple Color Emoji"',
        '"Segoe UI Emoji"',
        '"Segoe UI Symbol"',
        '"Noto Color Emoji"',
      ],
      fontWeight: {
        normal: '400',
        bold: '700',
      },
    },
    container: {
      center: true,
    },
    extend: {}
  },
  variants: {},
  plugins: [],
  corePlugins: {
    accessibility: false,
    backgroundAttachment: false,
    backgroundPosition: false,
    backgroundRepeat: false,
    backgroundSize: false,
    borderCollapse: false,
    cursor: false,
    fill: false,
    float: false,
    fontFamily: false,
    fontSmoothing: false,
    height: false,
    inset: false,
    letterSpacing: false,
    listStylePosition: false,
    listStyleType: false,
    maxHeight: false,
    minHeight: false,
    objectFit: false,
    objectPosition: false,
    opacity: false,
    order: false,
    outline: false,
    pointerEvents: false,
    position: false,
    resize: false,
    stroke: false,
    tableLayout: false,
    textTransform: false,
    userSelect: false,
    verticalAlign: false,
    visibility: false,
    whitespace: false,
    width: false,
    wordBreak: false,
    zIndex: false,
  }
}
